# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

# Default applications
$terminal = alacritty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$passwordManager = 1password
$messenger = signal-desktop
$webapp = $browser --app
$music = $webapp "https://music.youtube.com"

# Use defaults Omarchy defaults
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Extra autostart processes (uncomment to run Dropbox)
# exec-once = dropbox-cli start

# Extra bindings
bind = SUPER, A, exec, $webapp "https://claude.ai"

# Scroll faster in the terminal
windowrule = scroll_touchpad 1.5, match:class Alacritty
