source ~/.shell/init.sh

# load aliases and functions
source ~/.shell/aliases.sh
source ~/.shell/functions.sh

# bootstrap
source ~/.shell/bootstrap.sh

# load antibody plugins
source ~/.zsh_plugins.sh

# load zsh specific stuff
source ~/.zsh/completion.zsh
source ~/.zsh/prompt.zsh

# load company specific scripts
for file in ~/.dotfiles/company/*;
do
   source $file;
done
